from enum import IntEnum

VERSION = "v1.0.0"

BITCHAT_SERVICE_UUID = "f47b5e2d-4a9e-4c5a-9b3f-8e1d2c3a4b5c"
BITCHAT_CHARACTERISTIC_UUID = "a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"

COVER_TRAFFIC_PREFIX = "\u2602DUMMY\u2602"

FLAG_HAS_RECIPIENT = 0x01
FLAG_HAS_SIGNATURE = 0x02
FLAG_IS_COMPRESSED = 0x04

MSG_FLAG_IS_RELAY = 0x01
MSG_FLAG_IS_PRIVATE = 0x02
MSG_FLAG_HAS_ORIGINAL_SENDER = 0x04
MSG_FLAG_HAS_RECIPIENT_NICKNAME = 0x08
MSG_FLAG_HAS_SENDER_PEER_ID = 0x10
MSG_FLAG_HAS_MENTIONS = 0x20
MSG_FLAG_HAS_CHANNEL = 0x40
MSG_FLAG_IS_ENCRYPTED = 0x80

SIGNATURE_SIZE = 64
BROADCAST_RECIPIENT = b'\xFF' * 8

class DebugLevel(IntEnum):
    CLEAN = 0
    BASIC = 1
    FULL = 2

class MessageType(IntEnum):
    ANNOUNCE = 0x01
    KEY_EXCHANGE = 0x02
    LEAVE = 0x03
    MESSAGE = 0x04
    FRAGMENT_START = 0x05
    FRAGMENT_CONTINUE = 0x06
    FRAGMENT_END = 0x07
    CHANNEL_ANNOUNCE = 0x08
    CHANNEL_RETENTION = 0x09
    DELIVERY_ACK = 0x0A
    DELIVERY_STATUS_REQUEST = 0x0B
    READ_RECEIPT = 0x0C

__all__ = [
    'VERSION', 'BITCHAT_SERVICE_UUID', 'BITCHAT_CHARACTERISTIC_UUID',
    'COVER_TRAFFIC_PREFIX', 'FLAG_HAS_RECIPIENT', 'FLAG_HAS_SIGNATURE',
    'FLAG_IS_COMPRESSED', 'MSG_FLAG_IS_RELAY', 'MSG_FLAG_IS_PRIVATE',
    'MSG_FLAG_HAS_ORIGINAL_SENDER', 'MSG_FLAG_HAS_RECIPIENT_NICKNAME',
    'MSG_FLAG_HAS_SENDER_PEER_ID', 'MSG_FLAG_HAS_MENTIONS',
    'MSG_FLAG_HAS_CHANNEL', 'MSG_FLAG_IS_ENCRYPTED', 'SIGNATURE_SIZE',
    'BROADCAST_RECIPIENT', 'DebugLevel', 'MessageType'
]
